#! /bin/bash

if [ -z "$_FENZI_CONF_OPTIONS" ]; then
_FENZI_CONF_OPTIONS=0

source $CONFIG_DIR/fenzi_conf_lib

### OPTIONS ###           option    short   argc   default
add_opt OPT configuration help      h       0      ""                        \
"display this help and exit"
add_opt OPT configuration prefix    ""      1      "/usr/local"              \
"install architecture-independent files in prefix"
add_opt OPT configuration build     b       1      "DEBUG"                   \
"build type (DEBUG, PROFILE, RELEASE)"
add_opt OPT cuda          cudarch   ""      1      "sm_13"                   \
"cuda architecture (sm_13, sm_20)"
add_opt OPT simulation    tssize    ""      1      "small"                   \
"compile fenzi for a typical system size of tssize (vsmall, small, medium,"  \
"large, cco, custom)"
add_opt OPT simulation    maxnb     ""      1      580                       \
"maximum # of non-bonded neighbors"
add_opt OPT simulation    maxlatt   ""      1      64                       \
"maximum # of lattice neighbors"
add_opt OPT simulation    cblock    ""      1      ""                        \
"(custom only) cell blocksize"
add_opt OPT simulation    catoms    ""      1      ""                        \
"(custom only) cell atoms"
add_opt OPT simulation    maxdtype  ""      1      ""                        \
"(custom only) max # of dihedral types"
add_opt OPT simulation    maxatype  ""      1      ""                        \
"(custom only) max # of atom types"
add_opt OPT simulation    maxbtype  ""      1      ""                        \
"(custom only) max # of bond types"
add_opt OPT simulation    pconst     ""     0      "0"                         \
"run FEN ZI in npt ensamble - default nvt/nve"
add_opt OPT simulation    npt        ""     0      "0"                         \
"run FEN ZI in npt ensamble (shake works correctly) - default nvt/nve"
add_opt OPT simulation    consfix        "" 0      "0"                         \
"run FEN ZI with consfix - default no consfix"
### END OPTIONS ###

fi

